version: '3.5'

services:

    symfony: &symfony-template
      image: ${COMPOSE_PROJECT_NAME}-symfony:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: test
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-symfony
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./:/var/www/html:cached
      depends_on:
        - pgsql
        - mail
      networks:
        - symfony

    ###> doctrine/doctrine-bundle ###
    pgsql:
      image: postgres:${POSTGRES_VERSION:-14.10-bullseye}
      environment:
          POSTGRES_DB: ${POSTGRES_DB:-app}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dbuser01}
          POSTGRES_USER: ${POSTGRES_USER:-dbuser}
      ports:
        - "54321:5432"
      volumes:
          - ./var/postgresql-data:/var/lib/postgresql:delegated
          - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - symfony
    ###< doctrine/doctrine-bundle ###

    mail:
      image: axllent/mailpit:latest
      container_name: ${COMPOSE_PROJECT_NAME}-mail
      restart: always
      ports:
        - "8025:8025"
        - "1025:1025"
      networks:
        - symfony

networks:
  symfony:
    name: symfony